
server:
  port: 7002
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/book/**
          filters:
            - AuthenticationFilter

        - id: ShoppingCart-Service
          uri: lb://ShoppingCart-Service
          predicates:
            - Path=/carts/**
          filters:
            - AuthenticationFilter
























eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/













